-- One-sentence byline for a scheme, generated by the AI alongside the narrative.
-- Nullable: existing schemes predate this field and have no summary to backfill.
alter table schemes add column summary text;
